
import type { Config } from 'tailwindcss';

export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  safelist: [
    // These animations are referenced via inline style={{ animation: ... }} in JSX,
    // so Tailwind can't detect them during purge. We safelist the animate-* utilities
    // to ensure their @keyframes are included in the production build.
    'animate-softGlow',
    'animate-wcuCameraDrift',
    'animate-scanLine',
    'animate-wcuChartSpin',
    'animate-heroCameraDrift',
    'animate-panelFloat1',
    'animate-panelFloat2',
    'animate-panelFloat3',
    {
      pattern: /animate-(particleFloat|particleDriftHero|graphRise|chartRotate|dataLineUpdate|handMovement|wcuPanelActivate1|wcuPanelActivate2|wcuPanelActivate3|wcuDataBarAdjust|connectionLinePulse|wcuGraphUpdate|wcuParticleDrift|wcuHandPrecise)/,
    },
  ],
  theme: {
    extend: {
      animation: {
        heroZoom: "heroZoom 20s ease-in-out infinite alternate",
        floatOrb1: "floatOrb1 8s ease-in-out infinite",
        floatOrb2: "floatOrb2 10s ease-in-out infinite",
        floatOrb3: "floatOrb3 12s ease-in-out infinite",
        gridShift: "gridShift 15s linear infinite",
        heroCameraDrift: "heroCameraDrift 25s ease-in-out infinite",
        panelFloat1: "panelFloat1 10s ease-in-out infinite",
        panelFloat2: "panelFloat2 12s ease-in-out infinite",
        panelFloat3: "panelFloat3 11s ease-in-out infinite",
        softGlow: "softGlow 6s ease-in-out infinite",
        wcuCameraDrift: "wcuCameraDrift 28s ease-in-out infinite",
        scanLine: "scanLine 8s linear infinite",
        wcuChartSpin: "wcuChartSpin 10s linear infinite",
        // Animations used via inline style={{ animation: ... }}
        particleFloat: "particleFloat 3s ease-in-out infinite alternate",
        particleDriftHero: "particleDriftHero 5s ease-in-out infinite",
        graphRise: "graphRise 4s ease-in-out infinite",
        chartRotate: "chartRotate 10s linear infinite",
        dataLineUpdate: "dataLineUpdate 5s ease-in-out infinite",
        handMovement: "handMovement 8s ease-in-out infinite",
        wcuPanelActivate1: "wcuPanelActivate1 10s ease-in-out infinite",
        wcuPanelActivate2: "wcuPanelActivate2 12s ease-in-out infinite",
        wcuPanelActivate3: "wcuPanelActivate3 11s ease-in-out infinite",
        wcuDataBarAdjust: "wcuDataBarAdjust 5s ease-in-out infinite",
        connectionLinePulse: "connectionLinePulse 6s ease-in-out infinite",
        wcuGraphUpdate: "wcuGraphUpdate 4s ease-in-out infinite",
        wcuParticleDrift: "wcuParticleDrift 5s ease-in-out infinite",
        wcuHandPrecise: "wcuHandPrecise 8s ease-in-out infinite",
      },
      keyframes: {
        heroZoom: {
          "0%": { transform: "scale(1) translate(0, 0)" },
          "100%": { transform: "scale(1.08) translate(-1%, -1%)" },
        },
        floatOrb1: {
          "0%": { transform: "translate(0, 0) scale(1)" },
          "50%": { transform: "translate(60px, -40px) scale(1.15)" },
          "100%": { transform: "translate(0, 0) scale(1)" },
        },
        floatOrb2: {
          "0%": { transform: "translate(0, 0) scale(1)" },
          "50%": { transform: "translate(-50px, 30px) scale(1.1)" },
          "100%": { transform: "translate(0, 0) scale(1)" },
        },
        floatOrb3: {
          "0%": { transform: "translate(0, 0) scale(1)" },
          "50%": { transform: "translate(40px, 50px) scale(1.2)" },
          "100%": { transform: "translate(0, 0) scale(1)" },
        },
        particleFloat: {
          "0%": { transform: "translateY(0) scale(1)", opacity: "0.2" },
          "100%": { transform: "translateY(-30px) scale(1.5)", opacity: "0.6" },
        },
        gridShift: {
          "0%": { transform: "translate(0, 0)" },
          "100%": { transform: "translate(60px, 60px)" },
        },
        heroCameraDrift: {
          "0%": { transform: "scale(1.02) translate(0, 0)" },
          "25%": { transform: "scale(1.04) translate(-0.5%, 0.3%)" },
          "50%": { transform: "scale(1.03) translate(0.3%, -0.5%)" },
          "75%": { transform: "scale(1.05) translate(-0.3%, -0.2%)" },
          "100%": { transform: "scale(1.02) translate(0, 0)" },
        },
        panelFloat1: {
          "0%": { transform: "translate(0, 0) rotate(0deg)" },
          "33%": { transform: "translate(4px, -8px) rotate(0.3deg)" },
          "66%": { transform: "translate(-3px, -4px) rotate(-0.2deg)" },
          "100%": { transform: "translate(0, 0) rotate(0deg)" },
        },
        panelFloat2: {
          "0%": { transform: "translate(0, 0) rotate(0deg)" },
          "33%": { transform: "translate(-5px, -6px) rotate(-0.4deg)" },
          "66%": { transform: "translate(3px, -10px) rotate(0.3deg)" },
          "100%": { transform: "translate(0, 0) rotate(0deg)" },
        },
        panelFloat3: {
          "0%": { transform: "translate(0, 0) rotate(0deg)" },
          "33%": { transform: "translate(6px, -5px) rotate(0.2deg)" },
          "66%": { transform: "translate(-4px, -8px) rotate(-0.3deg)" },
          "100%": { transform: "translate(0, 0) rotate(0deg)" },
        },
        graphRise: {
          "0%": { transform: "scaleY(0.6)", opacity: "0.5" },
          "50%": { transform: "scaleY(1)", opacity: "1" },
          "100%": { transform: "scaleY(0.6)", opacity: "0.5" },
        },
        chartRotate: {
          "0%": { transform: "rotate(0deg)" },
          "100%": { transform: "rotate(360deg)" },
        },
        dataLineUpdate: {
          "0%": { transform: "scaleX(0.3)", opacity: "0.3" },
          "30%": { transform: "scaleX(1)", opacity: "1" },
          "60%": { transform: "scaleX(0.7)", opacity: "0.7" },
          "100%": { transform: "scaleX(0.3)", opacity: "0.3" },
        },
        softGlow: {
          "0%": { opacity: "0.15", transform: "scale(1)" },
          "50%": { opacity: "0.4", transform: "scale(1.15)" },
          "100%": { opacity: "0.15", transform: "scale(1)" },
        },
        particleDriftHero: {
          "0%": { transform: "translate(0, 0) scale(0.8)", opacity: "0" },
          "20%": { opacity: "0.6" },
          "80%": { opacity: "0.4" },
          "100%": { transform: "translate(var(--drift-x, 30px), var(--drift-y, -40px)) scale(1.2)", opacity: "0" },
        },
        handMovement: {
          "0%": { transform: "translate(0, 0) rotate(0deg)" },
          "25%": { transform: "translate(2px, -1px) rotate(0.5deg)" },
          "50%": { transform: "translate(-1px, 1px) rotate(-0.3deg)" },
          "75%": { transform: "translate(1px, -2px) rotate(0.2deg)" },
          "100%": { transform: "translate(0, 0) rotate(0deg)" },
        },
        wcuPanelActivate1: {
          "0%": { opacity: "0.7", transform: "translate(0, 0) scale(0.98)" },
          "15%": { opacity: "1", transform: "translate(3px, -6px) scale(1.01)" },
          "50%": { opacity: "1", transform: "translate(-2px, -4px) scale(1)" },
          "85%": { opacity: "0.85", transform: "translate(4px, -2px) scale(0.99)" },
          "100%": { opacity: "0.7", transform: "translate(0, 0) scale(0.98)" },
        },
        wcuPanelActivate2: {
          "0%": { opacity: "0.65", transform: "translate(0, 0) scale(0.97)" },
          "20%": { opacity: "0.7", transform: "translate(-3px, -3px) scale(0.98)" },
          "40%": { opacity: "1", transform: "translate(4px, -7px) scale(1.01)" },
          "70%": { opacity: "0.9", transform: "translate(-2px, -5px) scale(1)" },
          "100%": { opacity: "0.65", transform: "translate(0, 0) scale(0.97)" },
        },
        wcuPanelActivate3: {
          "0%": { opacity: "0.6", transform: "translate(0, 0) scale(0.96)" },
          "30%": { opacity: "0.65", transform: "translate(2px, -2px) scale(0.97)" },
          "55%": { opacity: "1", transform: "translate(-4px, -8px) scale(1.02)" },
          "80%": { opacity: "0.85", transform: "translate(3px, -4px) scale(1)" },
          "100%": { opacity: "0.6", transform: "translate(0, 0) scale(0.96)" },
        },
        wcuDataBarAdjust: {
          "0%": { transform: "scaleX(0.5) scaleY(0.7)" },
          "25%": { transform: "scaleX(0.8) scaleY(1)" },
          "50%": { transform: "scaleX(1) scaleY(0.85)" },
          "75%": { transform: "scaleX(0.65) scaleY(0.95)" },
          "100%": { transform: "scaleX(0.5) scaleY(0.7)" },
        },
        connectionLinePulse: {
          "0%": { opacity: "0", transform: "scaleX(0)" },
          "20%": { opacity: "0.8", transform: "scaleX(1)" },
          "80%": { opacity: "0.6", transform: "scaleX(1)" },
          "100%": { opacity: "0", transform: "scaleX(0)" },
        },
        wcuChartSpin: {
          "0%": { transform: "rotate(0deg)" },
          "100%": { transform: "rotate(-360deg)" },
        },
        wcuGraphUpdate: {
          "0%": { transform: "scaleY(0.5)" },
          "30%": { transform: "scaleY(0.9)" },
          "60%": { transform: "scaleY(1)" },
          "80%": { transform: "scaleY(0.7)" },
          "100%": { transform: "scaleY(0.5)" },
        },
        wcuParticleDrift: {
          "0%": { transform: "translate(0, 0)", opacity: "0" },
          "15%": { opacity: "0.5" },
          "85%": { opacity: "0.3" },
          "100%": { transform: "translate(var(--wcu-dx, 20px), var(--wcu-dy, -30px))", opacity: "0" },
        },
        wcuCameraDrift: {
          "0%": { transform: "scale(1.01) translate(0, 0)" },
          "25%": { transform: "scale(1.03) translate(0.3%, -0.2%)" },
          "50%": { transform: "scale(1.02) translate(-0.2%, 0.3%)" },
          "75%": { transform: "scale(1.04) translate(0.2%, 0.1%)" },
          "100%": { transform: "scale(1.01) translate(0, 0)" },
        },
        wcuHandPrecise: {
          "0%": { transform: "translate(0, 0)" },
          "20%": { transform: "translate(1px, -1.5px)" },
          "40%": { transform: "translate(-0.5px, 0.5px)" },
          "60%": { transform: "translate(1.5px, -0.5px)" },
          "80%": { transform: "translate(-1px, 1px)" },
          "100%": { transform: "translate(0, 0)" },
        },
        scanLine: {
          "0%": { top: "0%", opacity: "0" },
          "10%": { opacity: "0.4" },
          "90%": { opacity: "0.4" },
          "100%": { top: "100%", opacity: "0" },
        },
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
      },
      colors: {
        purple: {
          300: '#d8b4fe',
          400: '#c084fc',
          500: '#a855f7',
          600: '#9333ea',
          700: '#7e22ce',
        },
        gold: {
          300: '#fcd34d',
          400: '#fbbf24',
          500: '#f59e0b',
          600: '#d97706',
        },
        dark: {
          900: '#0a0a0a',
          800: '#141414',
          700: '#1a1a1a',
          600: '#262626',
        },
        neutral: {
          50: '#fafafa',
          100: '#f5f5f5',
          200: '#e5e5e5',
          300: '#d4d4d4',
          400: '#a3a3a3',
          500: '#737373',
          600: '#525252',
          700: '#404040',
          800: '#262626',
          900: '#171717',
        },
      },
    },
  },
  plugins: [],
} satisfies Config;
